# Generated by Django 6.0.3 on 2026-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('purchase_url', models.URLField(max_length=500)),
            ],
        ),
    ]
